name: Test Workflow

on:
  push:
    branches:
      - test_1  

jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print messages
        run: |
          "Impresión 1"
          "Impresión 2"
          "Impresión 3"
